// File generated by FlutterFire / Red Taxis Firebase configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKaEJNl_hDHj2Hvf28bTM6vsJm7WtMgI',
    appId: '1:211474359223:android:a484ed98fcf2a0cac2fe32',
    messagingSenderId: '211474359223',
    projectId: 'red-taxi-6b302',
    storageBucket: 'red-taxi-6b302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJTxpwZlzACqFiqrobWhGlZN4UVJTY2Y',
    appId: '1:211474359223:ios:9827c8e5edf2aef5c2fe32',
    messagingSenderId: '211474359223',
    projectId: 'red-taxi-6b302',
    storageBucket: 'red-taxi-6b302.firebasestorage.app',
    iosBundleId: 'com.redtaxis.driver.driverApp',
  );
}
